version: '3'
services:
  cf2dns:
    restart: always
    image: aaronlee/cf2dns:latest
    container_name: cf2dns
    volumes:
      - ./config/cronjob:/home/www/cronjob
      - ./config/cf2dns-v4.py:/home/www/cf2dns/cf2dns-v4.py
      - ./config/cf2dns-v6.py:/home/www/cf2dns/cf2dns-v6.py
